import { createElement } from 'lwc';
import VF_ThemMoi_Mon from 'c/vF_ThemMoi_Mon';

describe('c-v-f-them-moi-mon', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-v-f-them-moi-mon', {
            is: VF_ThemMoi_Mon
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});